"""edit user model

Revision ID: 27612ec0cdcd
Revises: f3d5656fd85c
Create Date: 2024-06-03 17:07:21.667074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27612ec0cdcd'
down_revision: Union[str, None] = 'f3d5656fd85c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('games_played', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('games_organized', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'games_organized')
    op.drop_column('user', 'games_played')
    # ### end Alembic commands ###
