"""add team creator

Revision ID: c22f27b2974f
Revises: 5b29427dda60
Create Date: 2024-05-08 23:55:03.673938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c22f27b2974f'
down_revision: Union[str, None] = '5b29427dda60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('creator', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'team', 'user', ['creator'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.drop_column('team', 'creator')
    # ### end Alembic commands ###
