"""add amount to game

Revision ID: 528630fe8d3d
Revises: 37ec310af163
Create Date: 2024-06-06 15:48:08.145271

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "528630fe8d3d"
down_revision: Union[str, None] = "37ec310af163"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game", sa.Column("amount", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game", "amount")
    # ### end Alembic commands ###
