"""Added games

Revision ID: e0ff669f2e6c
Revises: 2d9258464da7
Create Date: 2024-04-23 16:51:59.361603

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e0ff669f2e6c"
down_revision: Union[str, None] = "2d9258464da7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_status",
        sa.Column("code", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("opposite", sa.Integer(), nullable=True),
        sa.Column("outside_1", sa.Integer(), nullable=True),
        sa.Column("outside_2", sa.Integer(), nullable=True),
        sa.Column("setter", sa.Integer(), nullable=True),
        sa.Column("middle_1", sa.Integer(), nullable=True),
        sa.Column("middle_2", sa.Integer(), nullable=True),
        sa.Column("libero", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("place", sa.String(), nullable=False),
        sa.Column("datetime", sa.TIMESTAMP(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=True),
        sa.Column("team_1", sa.Integer(), nullable=True),
        sa.Column("team_2", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["status"],
            ["game_status.code"],
        ),
        sa.ForeignKeyConstraint(
            ["team_1"],
            ["team.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_2"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("game")
    op.drop_table("team")
    op.drop_table("game_status")
    # ### end Alembic commands ###
